// Copyright (C) 2024 The go-matter Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package mattertest

import (
	_ "embed"

	"github.com/cybergarage/go-matter/matter/config"
)

const (
	testAdministratorNodeID   = 0x0000000000000001
	testAdministratorFabricID = 0x0000000000000002
)

// Test-only certificate material generated by mattertest/certs/certgen.go
// (see mattertest/certs/Makefile), embedded into the test binary so it never
// depends on the working directory or on files being present on disk at
// test time.
var (
	//go:embed certs/admin-root-cert.pem
	testAdminRootCertPEM []byte
	//go:embed certs/admin-root-key.pem
	testAdminRootKeyPEM []byte
	//go:embed certs/admin-noc.pem
	testAdminNOCPEM []byte
	//go:embed certs/admin-private-key.pem
	testAdminPrivateKeyPEM []byte
)

// NewAdministratorConfig creates an AdministratorConfig from the embedded
// test certificates in mattertest/certs.
func NewAdministratorConfig() (config.AdministratorConfig, error) {
	return config.NewAdministratorConfig(
		config.WithAdministratorNodeID(testAdministratorNodeID),
		config.WithAdministratorFabricID(testAdministratorFabricID),
		config.WithAdministratorRootCertificate(testAdminRootCertPEM),
		config.WithAdministratorRootPrivateKey(testAdminRootKeyPEM),
		config.WithAdministratorNOC(testAdminNOCPEM),
		config.WithAdministratorPrivateKey(testAdminPrivateKeyPEM),
	), nil
}
