// Copyright (C) 2026 The go-matter Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package mockdevice

import (
	"context"
	"crypto/subtle"
	"encoding/binary"
	"fmt"

	"github.com/cybergarage/go-matter/matter/crypto"
	"github.com/cybergarage/go-matter/matter/encoding/message"
	"github.com/cybergarage/go-matter/matter/io"
	"github.com/cybergarage/go-matter/matter/protocol/pase/pake"
	"github.com/cybergarage/go-matter/matter/protocol/pase/pbkdf"
	"github.com/cybergarage/go-matter/matter/protocol/session"
	"github.com/cybergarage/go-matter/matter/types"
)

// sessionKeysSymmetricKeyLen matches pase.CryptoSymmetricKeyLen /
// caseprotocol's cryptoSymmetricKeyLen (128-bit AES-CCM keys) — duplicated
// here rather than imported since neither package exports its constant.
const sessionKeysSymmetricKeyLen = 16

// handlePASE runs this mock device's PASE responder role to completion over
// t, and returns a secure session (from the device's own point of view —
// already role-swapped, see swapRoleSessionKeys) once the handshake and its
// StatusReport succeed.
//
// This deliberately does not reuse matter/protocol/pase/pake's
// NewPake2Message: that constructor's computeCB substitutes the exchanged
// public values (pA, pB) in place of the real SPAKE2+ shared points Z/V — a
// pre-existing, verified stub (see its own doc comment) that produces a
// structurally valid but cryptographically wrong cB. This function computes
// Z/V for real via crypto.CryptoPAKESharedPointsResponder and builds Pake2
// from the low-level pake.NewPake2 struct instead.
//
// Pake1's pA and Pake3's cA are extracted via each message's exported Map()
// method: both fields have only an unexported accessor on their respective
// interfaces (pake.Pake1.pA / pake.Pake3.cA), which an external package
// like this one cannot call, but Map() is part of the exported
// Pake1/Pake3Helper contract and documented to carry the same field under
// that exact key.
func handlePASE(ctx context.Context, t io.Transport, passcode types.Passcode) (session.SecureSession, error) {
	// 1) PBKDFParamRequest
	reqBytes, err := t.Receive(ctx)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: receive PBKDFParamRequest: %w", err)
	}
	paramReq, err := pbkdf.NewParamRequestMessageFromBytes(reqBytes)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: decode PBKDFParamRequest: %w", err)
	}

	// 2) PBKDFParamResponse — salt/iterations/responderRandom/responderSessionID
	// are all auto-generated by NewParamResponse when omitted, exactly as a
	// real responder would generate them fresh.
	paramRes, err := pbkdf.NewParamResponseMessage(
		pbkdf.WithParamResponseMessageParamRequestMessage(paramReq),
	)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: build PBKDFParamResponse: %w", err)
	}
	resBytes, err := paramRes.Bytes()
	if err != nil {
		return nil, err
	}
	if err := t.Transmit(ctx, resBytes); err != nil {
		return nil, fmt.Errorf("mockdevice: transmit PBKDFParamResponse: %w", err)
	}

	// 3) Pake1: receive pA.
	pake1Bytes, err := t.Receive(ctx)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: receive Pake1: %w", err)
	}
	pake1Msg, err := pake.NewPake1MessageFromBytes(pake1Bytes)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: decode Pake1: %w", err)
	}
	pA, err := extractMapField(pake1Msg.Map(), "pake-1-struct", "pA")
	if err != nil {
		return nil, fmt.Errorf("mockdevice: Pake1: %w", err)
	}

	// 4) Compute the responder's SPAKE2+ values and Pake2's pB/cB for real.
	salt, ok := paramRes.PBKDFParams().Salt()
	if !ok {
		return nil, fmt.Errorf("mockdevice: PBKDFParamResponse missing salt")
	}
	iterations, ok := paramRes.PBKDFParams().Iterations()
	if !ok {
		return nil, fmt.Errorf("mockdevice: PBKDFParamResponse missing iterations")
	}
	w0, l, err := crypto.CryptoPAKEValuesResponder(passcode.Bytes(), salt, iterations)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: CryptoPAKEValuesResponder: %w", err)
	}
	y, err := crypto.CryptoPAKERandomScalar()
	if err != nil {
		return nil, fmt.Errorf("mockdevice: CryptoPAKERandomScalar: %w", err)
	}
	pB, err := crypto.CryptoPB(y, w0)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: CryptoPB: %w", err)
	}
	Z, V, err := crypto.CryptoPAKESharedPointsResponder(y, w0, l, pA)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: CryptoPAKESharedPointsResponder: %w", err)
	}
	tt, err := crypto.CryptoTranscript(paramReq.Payload(), paramRes.Payload(), pA, pB, Z, V, w0)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: CryptoTranscript: %w", err)
	}
	cAExpected, cB, Ke, err := crypto.CryptoP2(tt, pA, pB)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: CryptoP2: %w", err)
	}

	// 5) Pake2: send pB and cB, acknowledging Pake1.
	pake2 := pake.NewPake2(pake.WithPake2PB(pB), pake.WithPake2CB(cB))
	pake2Payload, err := pake2.Bytes()
	if err != nil {
		return nil, err
	}
	pake2Msg := message.NewMessage(
		message.WithMessageFrameHeader(message.NewHeader(
			message.WithHeaderSessionID(0),
			message.WithHeaderSecurityFlags(0x00),
			message.WithHeaderMessageCounter(message.NewMessageCounter()),
		)),
		message.WithMessageProtocolHeader(message.NewProtocolHeader(
			message.WithHeaderExchangeFlags(message.ReliabilityFlag),
			message.WithHeaderOpcode(message.PASEPake2),
			message.WithHeaderExchangeID(pake1Msg.ExchangeID()),
			message.WithHeaderProtocolID(message.SecureChannel),
			message.WithHeaderAckCounter(pake1Msg.MessageCounter()),
		)),
		message.WithMessagePayload(pake2Payload),
	)
	pake2Bytes, err := pake2Msg.Bytes()
	if err != nil {
		return nil, err
	}
	if err := t.Transmit(ctx, pake2Bytes); err != nil {
		return nil, fmt.Errorf("mockdevice: transmit Pake2: %w", err)
	}

	// 6) Pake3: receive and verify cA.
	pake3Bytes, err := t.Receive(ctx)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: receive Pake3: %w", err)
	}
	pake3Msg, err := pake.NewPake3MessageFromBytes(pake3Bytes)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: decode Pake3: %w", err)
	}
	cAReceived, err := extractMapField(pake3Msg.Map(), "pake-3-struct", "cA")
	if err != nil {
		return nil, fmt.Errorf("mockdevice: Pake3: %w", err)
	}
	if subtle.ConstantTimeCompare(cAReceived, cAExpected) != 1 {
		if err := sendPASEStatusReportFailure(ctx, t, pake3Msg.ExchangeID()); err != nil {
			return nil, err
		}
		return nil, fmt.Errorf("mockdevice: PASE cA mismatch")
	}

	// 7) StatusReport: success.
	if err := sendPASEStatusReportSuccess(ctx, t, pake3Msg.ExchangeID(), pake3Msg.MessageCounter()); err != nil {
		return nil, err
	}

	// 8) Derive session keys from Ke, exactly as the initiator does
	// (matter/protocol/pase/initiator.go), then present the device's own
	// (role-swapped) view of them.
	derived, err := crypto.CryptoKDF(Ke, nil, []byte("SessionKeys"), 3*sessionKeysSymmetricKeyLen)
	if err != nil {
		return nil, fmt.Errorf("mockdevice: derive PASE session keys: %w", err)
	}
	natural := simpleSessionKeys{
		i2rKey:               derived[0:sessionKeysSymmetricKeyLen],
		r2iKey:               derived[sessionKeysSymmetricKeyLen : 2*sessionKeysSymmetricKeyLen],
		attestationChallenge: derived[2*sessionKeysSymmetricKeyLen : 3*sessionKeysSymmetricKeyLen],
		initiatorSessionID:   session.SessionID(paramReq.InitiatorSessionID()),
		responderSessionID:   session.SessionID(paramRes.ResponderSessionID()),
		localNodeID:          0,
		peerNodeID:           0,
	}

	return session.NewSecureSession(t, swapRoleSessionKeys(natural)), nil
}

// extractMapField reads a []byte value nested two levels deep in a message
// Map() (as pake1Message/pake3Message's Map() implementations nest their
// underlying Pake1/Pake3 struct's own Map() under a "pake-N-struct" key) —
// used because Pake1.pA()/Pake3.cA() are unexported methods on otherwise
// exported interfaces, unreachable from outside the pake package, while
// Map() is the documented, exported way to read the same field.
func extractMapField(m map[string]any, structKey, fieldKey string) ([]byte, error) {
	inner, ok := m[structKey].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing %q in Map()", structKey)
	}
	b, ok := inner[fieldKey].([]byte)
	if !ok || len(b) == 0 {
		return nil, fmt.Errorf("missing %q in Map()[%q]", fieldKey, structKey)
	}
	return b, nil
}

func sendPASEStatusReportSuccess(ctx context.Context, t io.Transport, exchangeID message.ExchangeID, ackedCounter message.MessageCounter) error {
	return sendPASEStatusReport(ctx, t, exchangeID, ackedCounter, 0, 0)
}

func sendPASEStatusReportFailure(ctx context.Context, t io.Transport, exchangeID message.ExchangeID) error {
	return sendPASEStatusReport(ctx, t, exchangeID, 0, 1 /* FAILURE */, 0)
}

// sendPASEStatusReport builds and sends a fixed-width, little-endian
// StatusReport payload — NOT TLV, matching connectedhomeip's
// StatusReport::Parse and this repo's own pase.Initiator.parseStatusReport.
func sendPASEStatusReport(ctx context.Context, t io.Transport, exchangeID message.ExchangeID, ackedCounter message.MessageCounter, generalCode, protocolCode uint16) error {
	payload := make([]byte, 8)
	binary.LittleEndian.PutUint16(payload[0:2], generalCode)
	binary.LittleEndian.PutUint32(payload[2:6], uint32(message.SecureChannel))
	binary.LittleEndian.PutUint16(payload[6:8], protocolCode)

	headerOpts := []message.ProtocolHeaderOption{
		message.WithHeaderExchangeFlags(message.ReliabilityFlag),
		message.WithHeaderOpcode(message.StatusReport),
		message.WithHeaderExchangeID(exchangeID),
		message.WithHeaderProtocolID(message.SecureChannel),
	}
	if ackedCounter != 0 {
		headerOpts = append(headerOpts, message.WithHeaderAckCounter(ackedCounter))
	}

	msg := message.NewMessage(
		message.WithMessageFrameHeader(message.NewHeader(
			message.WithHeaderSessionID(0),
			message.WithHeaderSecurityFlags(0x00),
			message.WithHeaderMessageCounter(message.NewMessageCounter()),
		)),
		message.WithMessageProtocolHeader(message.NewProtocolHeader(headerOpts...)),
		message.WithMessagePayload(payload),
	)
	wire, err := msg.Bytes()
	if err != nil {
		return err
	}
	return t.Transmit(ctx, wire)
}
